plugins {
    kotlin("jvm") version "2.2.20" apply false
    id("com.android.library") version "8.11.1" apply false
    id("com.android.application") version "8.11.1" apply false
    id("org.jetbrains.kotlin.android") version "2.2.20" apply false
    id("org.jetbrains.kotlin.plugin.compose") version "2.2.20" apply false
    id("org.jetbrains.dokka-javadoc") version "2.2.0" apply false
    id("org.jetbrains.kotlinx.binary-compatibility-validator") version "0.18.1"
}

apiValidation {
    ignoredProjects.add("example")
}

allprojects {
    group = "com.zhumeng"
    version = "0.1.0"
}

subprojects {
    val centralUsername = providers.gradleProperty("mavenCentralUsername")
        .orElse(providers.environmentVariable("MAVEN_CENTRAL_USERNAME"))
    val centralPassword = providers.gradleProperty("mavenCentralPassword")
        .orElse(providers.environmentVariable("MAVEN_CENTRAL_PASSWORD"))
    val signingKey = providers.gradleProperty("signingKey")
        .orElse(providers.environmentVariable("SIGNING_KEY"))
    val signingPassword = providers.gradleProperty("signingPassword")
        .orElse(providers.environmentVariable("SIGNING_PASSWORD"))

    fun PublishingExtension.configureReleaseRepositories() {
        repositories {
            maven {
                name = "workspace"
                url = rootProject.layout.buildDirectory.dir("maven-repository").get().asFile.toURI()
            }
            maven {
                name = "mavenCentral"
                url = uri(
                    providers.gradleProperty("mavenCentralUrl").orElse(
                        "https://ossrh-staging-api.central.sonatype.com/service/local/staging/deploy/maven2/",
                    ).get(),
                )
                credentials {
                    username = centralUsername.orNull
                    password = centralPassword.orNull
                }
            }
        }
    }

    fun MavenPublication.configurePom() {
        pom {
            name.set("Kanvas ${project.name}")
            description.set("A modular, extensible K-line chart library built with Jetpack Compose.")
            url.set("https://github.com/zhumeng1582/Kanvas")
            licenses {
                license {
                    name.set("The Apache License, Version 2.0")
                    url.set("https://www.apache.org/licenses/LICENSE-2.0.txt")
                }
            }
            scm {
                connection.set("scm:git:https://github.com/zhumeng1582/Kanvas.git")
                developerConnection.set("scm:git:ssh://git@github.com/zhumeng1582/Kanvas.git")
                url.set("https://github.com/zhumeng1582/Kanvas")
            }
            developers {
                developer {
                    id.set("zhumeng")
                    name.set("zhumeng")
                }
            }
        }
    }

    pluginManager.withPlugin("org.jetbrains.kotlin.jvm") {
        apply(plugin = "maven-publish")
        apply(plugin = "signing")
        apply(plugin = "org.jetbrains.dokka-javadoc")
        val dokkaJavadocJar = tasks.register<Jar>("dokkaJavadocJar") {
            description = "A Javadoc JAR generated by Dokka."
            dependsOn("dokkaGeneratePublicationJavadoc")
            from(layout.buildDirectory.dir("dokka/javadoc"))
            archiveClassifier.set("javadoc")
        }
        extensions.configure<JavaPluginExtension> {
            withSourcesJar()
        }
        extensions.configure<PublishingExtension> {
            publications {
                create<MavenPublication>("release") {
                    from(components["java"])
                    artifactId = project.name
                    artifact(dokkaJavadocJar)
                    configurePom()
                }
            }
            configureReleaseRepositories()
        }
        extensions.configure<SigningExtension> {
            if (signingKey.isPresent) {
                useInMemoryPgpKeys(signingKey.get(), signingPassword.orNull)
                sign(extensions.getByType<PublishingExtension>().publications)
            }
        }
    }

    pluginManager.withPlugin("com.android.library") {
        apply(plugin = "maven-publish")
        apply(plugin = "signing")
        apply(plugin = "org.jetbrains.dokka-javadoc")
        val dokkaJavadocJar = tasks.register<Jar>("dokkaJavadocJar") {
            description = "A Javadoc JAR generated by Dokka."
            dependsOn("dokkaGeneratePublicationJavadoc")
            from(layout.buildDirectory.dir("dokka/javadoc"))
            archiveClassifier.set("javadoc")
        }
        extensions.configure<com.android.build.gradle.LibraryExtension> {
            publishing {
                singleVariant("release") {
                    withSourcesJar()
                }
            }
            defaultConfig {
                consumerProguardFiles(rootProject.file("consumer-rules.pro"))
            }
        }
        afterEvaluate {
            extensions.configure<PublishingExtension> {
                publications {
                    create<MavenPublication>("release") {
                        from(components["release"])
                        artifactId = project.name
                        artifact(dokkaJavadocJar)
                        configurePom()
                    }
                }
                configureReleaseRepositories()
            }
            extensions.configure<SigningExtension> {
                if (signingKey.isPresent) {
                    useInMemoryPgpKeys(signingKey.get(), signingPassword.orNull)
                    sign(extensions.getByType<PublishingExtension>().publications)
                }
            }
        }
    }
}

/**
 * Guards the Maven-facing dependency contract. Public signatures in Core,
 * Compose and Drawing expose these libraries, so publishing them with runtime
 * scope would leave non-Gradle and isolated consumers without a compile
 * classpath that can load the Kanvas API.
 */
tasks.register("verifyPublishedPomScopes") {
    group = "verification"
    description = "Checks that dependencies exposed by the public API use Maven compile scope."
    dependsOn(
        ":kanvas-core:generatePomFileForReleasePublication",
        ":kanvas-compose:generatePomFileForReleasePublication",
        ":kanvas-drawing:generatePomFileForReleasePublication",
    )

    doLast {
        fun verify(projectName: String, expectedCompileArtifacts: Set<String>) {
            val pom = project(projectName).layout.buildDirectory
                .file("publications/release/pom-default.xml")
                .get()
                .asFile
            val document = javax.xml.parsers.DocumentBuilderFactory.newInstance()
                .newDocumentBuilder()
                .parse(pom)
            val dependencies = document.getElementsByTagName("dependency")
            val scopes = buildMap {
                for (index in 0 until dependencies.length) {
                    val dependency = dependencies.item(index) as org.w3c.dom.Element
                    fun textOf(tag: String): String? = dependency
                        .getElementsByTagName(tag)
                        .item(0)
                        ?.textContent
                    val artifact = textOf("artifactId") ?: continue
                    put(artifact, textOf("scope"))
                }
            }
            expectedCompileArtifacts.forEach { artifact ->
                check(scopes[artifact] == "compile") {
                    "$projectName publishes $artifact with scope=${scopes[artifact]}; expected compile"
                }
            }
        }

        verify(":kanvas-core", setOf("kotlinx-coroutines-core-jvm"))
        verify(
            ":kanvas-compose",
            setOf("animation-core", "runtime", "foundation", "ui", "ui-graphics", "ui-text"),
        )
        verify(
            ":kanvas-drawing",
            setOf("runtime", "foundation", "ui", "ui-graphics"),
        )
    }
}
